/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        surface: '#161616',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d2c5b0',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#9b8f7c',
        'outline-variant': '#4e4635',
        'surface-tint': '#f0c04d',
        primary: '#ffe4af',
        'on-primary': '#3f2e00',
        'primary-container': '#f5c451',
        'on-primary-container': '#6d5100',
        'inverse-primary': '#785a00',
        secondary: '#ffb3b0',
        'on-secondary': '#68000f',
        'secondary-container': '#901822',
        'on-secondary-container': '#ff9e9b',
        tertiary: '#cbecff',
        'on-tertiary': '#003547',
        'tertiary-container': '#7fd5ff',
        'on-tertiary-container': '#005c7a',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffdf9d',
        'primary-fixed-dim': '#f0c04d',
        'on-primary-fixed': '#251a00',
        'on-primary-fixed-variant': '#5b4300',
        'secondary-fixed': '#ffdad8',
        'secondary-fixed-dim': '#ffb3b0',
        'on-secondary-fixed': '#410006',
        'on-secondary-fixed-variant': '#8c1520',
        'tertiary-fixed': '#c0e8ff',
        'tertiary-fixed-dim': '#7bd1fb',
        'on-tertiary-fixed': '#001e2b',
        'on-tertiary-fixed-variant': '#004d66',
        background: '#131313',
        'on-background': '#e5e2e1',
        'glass-border': 'rgba(255, 255, 255, 0.12)',
        'text-primary': '#FFFFFF',
        'text-secondary': '#A1A1AA',
        'background-blur': 'rgba(9, 9, 9, 0.7)',
      },
      fontFamily: {
        sans: ['Inter_400Regular'],
        'sans-medium': ['Inter_500Medium'],
        'sans-semibold': ['Inter_600SemiBold'],
        'sans-bold': ['Inter_700Bold'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl-mobile': [
          '36px',
          { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        caption: ['13px', { lineHeight: '18px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-page': '24px',
        'margin-mobile': '16px',
        gutter: '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'section-gap': '48px',
      },
    },
  },
  plugins: [],
};
